# Generated by Django 5.1.6 on 2025-02-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descr', models.TextField()),
                ('price', models.IntegerField()),
                ('bool', models.BooleanField(default=False)),
            ],
        ),
    ]
