# Generated by Django 5.1.6 on 2025-02-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('food_preference', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='customer_photos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Make',
        ),
    ]
