# Generated by Django 5.1.6 on 2025-02-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0003_fooddescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodDescription',
            new_name='Food',
        ),
    ]
