# Generated by Django 5.1.6 on 2025-02-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0005_category_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.CharField(max_length=70),
        ),
    ]
