# Generated by Django 5.1.6 on 2025-02-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0006_alter_food_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(to='E_commerce.category'),
        ),
    ]
