# Generated by Django 5.1.6 on 2025-02-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0007_remove_food_category_alter_food_price_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
