# Generated by Django 5.1.6 on 2025-02-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0009_foodorder_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
    ]
