# Generated by Django 5.1.6 on 2025-02-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0010_remove_food_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
