# Generated by Django 5.1.5 on 2025-03-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0014_foodordera_delete_foodorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodordera',
            old_name='photo',
            new_name='transaction',
        ),
        migrations.RemoveField(
            model_name='foodordera',
            name='total_price',
        ),
        migrations.AddField(
            model_name='foodordera',
            name='your_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
