# Generated by Django 5.1.5 on 2025-04-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0016_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('burger', 'burger'), ('pizza', 'pizza'), ('pasta', 'pasta'), ('fries', 'fries')], default='pizza', max_length=20),
        ),
    ]
