# Generated by Django 5.1.5 on 2025-04-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0017_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('pizza', 'Pizaa'), ('burger', 'Burger'), ('pasta', 'Pasta'), ('mokerony', 'Mokerony')], default='pizza', max_length=20),
        ),
    ]
