# Generated by Django 5.1.5 on 2025-04-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0022_deviceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
