"""
Django settings for mybackend project.
Generated by 'django-admin startproject' using Django 5.1.5.
"""

import os
from pathlib import Path
import dj_database_url

# BASE DIR
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
SECRET_KEY = 'django-insecure-hlwht!-m_2^u^_hx-87qd3_^fmwr-)ncn*$o$n$y+y$j_%3!ke'
DEBUG = True
ALLOWED_HOSTS = []

# CORS
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React frontend
]

# APPLICATIONS
INSTALLED_APPS = [
    'channels',
    'E_commerce.apps.ECommerceConfig',
    'api',
    
    # Django default
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # 3rd-party
    'admin_interface',
    'colorfield',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

SITE_ID = 1

# MIDDLEWARE
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# X-FRAME OPTIONS
X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

# URLS
ROOT_URLCONF = 'mybackend.urls'
WSGI_APPLICATION = 'mybackend.wsgi.application'
ASGI_APPLICATION = 'E_commerce.asgi.application'

# TEMPLATES
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'my_db',
        'USER': 'newuser',
        'PASSWORD': 'QAZwsx123#',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}
# AUTHENTICATION
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# PASSWORD VALIDATION
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# INTERNATIONALIZATION
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
APPEND_SLASH = False

# STATIC FILES
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

# MEDIA
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# DJANGO ALLAUTH CONFIG
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '841863....365535-68kji834...rg8tqcq.apps.geuser....content.com',
            'client_secret': 'OCSPX-W7....QfqZRgX..........gYDRXS61g8',
            'key': ''
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_SIGNUP_FIELDS = ["email", "password1", "password2"]

LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "about"
LOGIN_URL = '/accounts/login/'

# TWILIO
TWILIO_ACCOUNT_SID = 'ACfb8c6b6...5bddbb4c9044845e8a7e7'
TWILIO_AUTH_TOKEN = '9bb8a65ac1...c664f763cb4c5a24ba'
TWILIO_PHONE_NUMBER = '+154...48701'
ADMIN_PHONE_NUMBER = '+251914243851'

# AUTO FIELD
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
